import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./component/NavBar";
import Footer from "./component/Footer";
import GenAIEnrollModal from "./component/ModalForm";
import BackToTop from "./component/BackToTop";
import StickyWhatsApp from "./component/StickyWhatsApp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Job Gurantee Program",
  description: "Generated by create next app",
};
export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};
export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      
      <body className="min-h-full flex flex-col">
        <Navbar/>
        {children}

        <Footer/>
        <GenAIEnrollModal/>
        <StickyWhatsApp/>
        <BackToTop/>
      </body>

    </html>
  );
}
